name: Simple workflow

on:
  push:
    branches:
    - main
  workflow_dispatch: 


jobs:
  deploy:
    environment: prod
    name: Simple workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: List items
        run: ls -s

